Switch to erlef/setup-beam@v1
Don’t update to Ubuntu 22.04 yet. The currently specified OTP version,
22.3, does not run on Ubuntu 22.04, as per [1].

This is an attempt to fix the following error that occurred when running
on Ubuntu 22.04:

    Error: 19:51:19.461 [error] Unable to load crypto library. Failed
    with error:
    ":load_failed, Failed to load NIF library
    /home/runner/work/_temp/.setup-elixir/otp/lib/crypto-4.6.5/priv/lib/crypto:
    'libcrypto.so.1.0.0: cannot open shared object file: No such file or
    directory'"
    OpenSSL might not be installed on this system.

[1]: https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp